
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.main.admin.enabled=true

# Actuator.metrics.export.prometheus.enabled=true

jpa.properties.hibernate.format_sql=true
jpa.properties.eclipselink.ddl-generation=create-tables


---


# logging.file=/tmp/logs/app.log
logging.level=INFO

management.server.port=8080

spring.jackson.serialization.write_dates_as_timestamps=false

management.endpoints.web.exposure.include=*

spring.jmx.enabled=true

management.httptrace.include=REQUEST_HEADERS,RESPONSE_HEADERS,PRINCIPAL,REMOTE_ADDRESS,SESSION_ID

spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.main.admin.enabled=true

---

Actuator.metrics.export.prometheus.enabled=true

jpa.properties.hibernate.format_sql=true
jpa.properties.eclipselink.ddl-generation=create-tables